"""empty message

Revision ID: 898ae0c70ac1
Revises: 3f14295dbb09
Create Date: 2022-04-25 21:01:50.375344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898ae0c70ac1'
down_revision = '3f14295dbb09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_planets', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_planets'], ['planets.uid'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_planets')
    # ### end Alembic commands ###
