"""empty message

Revision ID: 8a09700700bf
Revises: c32ca2a00f89
Create Date: 2022-04-23 17:08:47.379565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a09700700bf'
down_revision = 'c32ca2a00f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fav_people', sa.Column('id_people', sa.Integer(), nullable=True))
    op.drop_constraint('fav_people_ibfk_2', 'fav_people', type_='foreignkey')
    op.create_foreign_key(None, 'fav_people', 'people', ['id_people'], ['uid'])
    op.drop_column('fav_people', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fav_people', sa.Column('name', mysql.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'fav_people', type_='foreignkey')
    op.create_foreign_key('fav_people_ibfk_2', 'fav_people', 'people', ['name'], ['name'])
    op.drop_column('fav_people', 'id_people')
    # ### end Alembic commands ###
