"""empty message

Revision ID: 8f26c13c90e6
Revises: 97a406690b0d
Create Date: 2022-04-22 00:26:00.450671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f26c13c90e6'
down_revision = '97a406690b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fav_people', sa.Column('id_user', sa.Integer(), nullable=True))
    op.drop_constraint('fav_people_ibfk_1', 'fav_people', type_='foreignkey')
    op.create_foreign_key(None, 'fav_people', 'user', ['id_user'], ['id'])
    op.drop_column('fav_people', 'id_use')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fav_people', sa.Column('id_use', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fav_people', type_='foreignkey')
    op.create_foreign_key('fav_people_ibfk_1', 'fav_people', 'user', ['id_use'], ['id'])
    op.drop_column('fav_people', 'id_user')
    # ### end Alembic commands ###
