"""empty message

Revision ID: 97a406690b0d
Revises: 0f1a84abd5fc
Create Date: 2022-04-21 23:46:31.746476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a406690b0d'
down_revision = '0f1a84abd5fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid_people', sa.Integer(), nullable=True),
    sa.Column('id_use', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_use'], ['user.id'], ),
    sa.ForeignKeyConstraint(['uid_people'], ['people.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_people')
    # ### end Alembic commands ###
