"""empty message

Revision ID: bb6a745d6acc
Revises: 0d8543e9d53a
Create Date: 2022-04-20 20:32:13.904714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb6a745d6acc'
down_revision = '0d8543e9d53a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('rotation', sa.Integer(), nullable=True))
    op.add_column('planets', sa.Column('orbital', sa.Integer(), nullable=True))
    op.drop_column('planets', 'rotation_period')
    op.drop_column('planets', 'orbital_period')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('orbital_period', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('planets', sa.Column('rotation_period', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('planets', 'orbital')
    op.drop_column('planets', 'rotation')
    # ### end Alembic commands ###
