"""empty message

Revision ID: c32ca2a00f89
Revises: 8da6e5481082
Create Date: 2022-04-23 16:33:32.703415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c32ca2a00f89'
down_revision = '8da6e5481082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fav_people', sa.Column('name', sa.String(length=120), nullable=True))
    op.drop_constraint('fav_people_ibfk_2', 'fav_people', type_='foreignkey')
    op.create_foreign_key(None, 'fav_people', 'people', ['name'], ['name'])
    op.drop_column('fav_people', 'uid_people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fav_people', sa.Column('uid_people', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fav_people', type_='foreignkey')
    op.create_foreign_key('fav_people_ibfk_2', 'fav_people', 'people', ['uid_people'], ['uid'])
    op.drop_column('fav_people', 'name')
    # ### end Alembic commands ###
